# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e6e0a319ee2810fd1ee4acd46497a30"
name = "aurea-dev-application"
handle = "aurea-dev-application"
application_url = "https://concerns-nv-gathering-player.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aurea-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://concerns-nv-gathering-player.trycloudflare.com/auth/callback",
  "https://concerns-nv-gathering-player.trycloudflare.com/auth/shopify/callback",
  "https://concerns-nv-gathering-player.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
